CREATE TABLE `tbl_account` (
	`account_id` int AUTO_INCREMENT NOT NULL,
	`account_id_md5` varchar(35) NOT NULL,
	`lead_id` int,
	`vendor_id` int,
	`user_type` int NOT NULL DEFAULT 1,
	`created_by` int NOT NULL,
	`user_admin_id` int NOT NULL,
	`old_user_admin_id` int,
	`account_name` varchar(255) NOT NULL,
	`contact_person_name` varchar(255) NOT NULL,
	`ac_type` int NOT NULL,
	`cust_type` int NOT NULL DEFAULT 1,
	`member_type` int NOT NULL DEFAULT 0,
	`website` varchar(100) NOT NULL,
	`email` varchar(100) NOT NULL,
	`fax` varchar(20) NOT NULL,
	`industry` int NOT NULL,
	`annual_revenue` int NOT NULL,
	`account_owner` int NOT NULL,
	`parent_account` int NOT NULL,
	`rating` int NOT NULL,
	`phone` varchar(100) NOT NULL,
	`alternate_phone` varchar(20),
	`ownership` int NOT NULL,
	`no_of_employee` int NOT NULL,
	`sic_code` varchar(50) NOT NULL,
	`description` text NOT NULL,
	`created_at` datetime NOT NULL,
	`status` int NOT NULL,
	`is_shift` tinyint NOT NULL DEFAULT 0,
	`masterID` int DEFAULT 0,
	`gst_uin_number` varchar(40),
	`state_code` varchar(50) NOT NULL,
	`pan_it_number` varchar(40),
	`company_logo` varchar(80),
	`address` varchar(255),
	`state` varchar(40),
	`country` varchar(40),
	`ctry_isd_code` varchar(10) NOT NULL DEFAULT '91',
	`zipcode` varchar(10),
	`bank_name` varchar(40),
	`bank_branch` varchar(40),
	`account_number` varchar(40),
	`ifsc_code` varchar(20),
	`account_unique_id` varchar(20),
	`source` int NOT NULL,
	`old_source` int NOT NULL DEFAULT 0,
	`fb_page_name` varchar(255) NOT NULL,
	`deals_in` text NOT NULL,
	`stopService` enum('N','Y') NOT NULL DEFAULT 'N',
	`stopServiceDate` datetime,
	`unblockServiceDate` datetime,
	`not_now_later` enum('N','Y') NOT NULL DEFAULT 'N',
	`sent_wa_template_id` varchar(255) NOT NULL,
	`wa_template_count` int NOT NULL,
	`wa_template_sent_dt` datetime NOT NULL,
	`is_xls` enum('Y','N') NOT NULL DEFAULT 'N',
	`is_shift_portal` varchar(20) NOT NULL DEFAULT 'N',
	`is_deleted` tinyint NOT NULL DEFAULT 0,
	CONSTRAINT `tbl_account_account_id` PRIMARY KEY(`account_id`)
);
--> statement-breakpoint
CREATE TABLE `tbl_employees` (
	`emp_id` int AUTO_INCREMENT NOT NULL,
	`mem_key` varchar(100),
	`created_by` int NOT NULL,
	`parent_id` int NOT NULL,
	`user_type` enum('1','2') NOT NULL DEFAULT '2',
	`register_type` enum('D','T','R','P') NOT NULL DEFAULT 'D',
	`portal_name` varchar(50) NOT NULL DEFAULT 'WI',
	`title` varchar(10),
	`first_name` varchar(50) NOT NULL,
	`middle_name` varchar(50),
	`last_name` varchar(50) NOT NULL,
	`email` varchar(100) NOT NULL,
	`old_email` varchar(100),
	`password` varchar(50) NOT NULL,
	`phone_number` varchar(15),
	`designation` int NOT NULL,
	`signature_designation` varchar(255) NOT NULL,
	`address` varchar(255),
	`bank_details` text,
	`isd_code` int NOT NULL DEFAULT 0,
	`timezone` varchar(200) NOT NULL DEFAULT 'Asia/Kolkata',
	`tmp_isd_code` int,
	`tmp_timezone` varchar(255),
	`user_limit` int NOT NULL,
	`deal_stage_limit` int NOT NULL DEFAULT 15,
	`lead_stage_limit` int NOT NULL DEFAULT 15,
	`created_at` datetime NOT NULL,
	`last_login_date` varchar(30),
	`current_login` varchar(30),
	`default_currency` int,
	`default_currency_name` varchar(50),
	`time_slot` int NOT NULL,
	`working_days` varchar(50) NOT NULL,
	`is_verified` enum('1','2') NOT NULL DEFAULT '2',
	`status` enum('0','1','2') NOT NULL DEFAULT '1',
	`status_dt_tm` datetime,
	`paid_status` int NOT NULL DEFAULT 0,
	`verified_dt_tm` datetime NOT NULL,
	`auto_regs_from_ei` tinyint NOT NULL DEFAULT 0,
	`api_key_ei` varchar(255) NOT NULL,
	`membership_end_date` date NOT NULL,
	`extend_expiry_date` date NOT NULL,
	`seven_day_mail_status` enum('Y','N') NOT NULL DEFAULT 'N',
	`three_day_mail_status` enum('Y','N') NOT NULL DEFAULT 'N',
	`one_day_mail_status` enum('Y','N') NOT NULL DEFAULT 'N',
	`invoice_template` int NOT NULL DEFAULT 1,
	`calling_membership` char(1) NOT NULL DEFAULT 'N',
	`calling_username` varchar(255) NOT NULL,
	`callig_password` varchar(255) NOT NULL,
	`calling_extn` int NOT NULL,
	`supp_amt_show` char(1) NOT NULL DEFAULT 'N',
	`sales_inv_prefix_txt` varchar(30),
	`purchase_inv_prefix_txt` varchar(30),
	`credit_inv_prefix_txt` varchar(30),
	`debit_inv_prefix_txt` varchar(30),
	`sales_order_prefix_txt` varchar(30),
	`purchase_order_prefix_txt` varchar(30),
	`performa_inv_prefix_txt` varchar(30),
	`delivery_note_prefix_txt` varchar(30),
	`loginid_chg_dt` datetime NOT NULL,
	`is_pop_show_acnt` tinyint DEFAULT 0,
	`whatsapp_no_optin` char(1) NOT NULL DEFAULT 'N',
	`whatsapp_send_from_wi` char(1) NOT NULL DEFAULT 'N',
	`whatsapp_send_from_wi_dt` datetime NOT NULL,
	`whatsapp_permission` char(1) NOT NULL DEFAULT 'N',
	`whatsapp_wabano` varchar(255) NOT NULL,
	`old_whatsapp_wabano` varchar(255) NOT NULL,
	`whatsapp_vendor` char(1) NOT NULL DEFAULT 'N',
	`whatsapp_api_username` text NOT NULL,
	`whatsapp_api_password` varchar(255) NOT NULL,
	`wp_type` enum('crm','erp','ecom','pi','eismo','reismo','ttwsmo','pismo','wlsmo','ttw','O','N') NOT NULL DEFAULT 'N',
	`whatsapp_app_id` varchar(255) NOT NULL,
	`wa_login_username` varchar(255) NOT NULL,
	`wa_api_key_dt` date NOT NULL,
	`wa_token_exp_dt` datetime NOT NULL,
	`whatsapp_bulk_permission` enum('N','Y') NOT NULL DEFAULT 'N',
	`whatsapp_template_limit` int NOT NULL,
	`tempSta` char(1) NOT NULL DEFAULT 'N',
	`temp_mail_sent` char(1) NOT NULL DEFAULT 'N',
	`wa_member_type` char(1) NOT NULL DEFAULT 'N',
	`wa_emp_mem_type` int NOT NULL,
	`waba_activated` char(1) NOT NULL DEFAULT 'N',
	`wp_mm_lite_enabled` char(1) NOT NULL DEFAULT 'N',
	`customer_type` char(1) NOT NULL DEFAULT 'N',
	`domain_url` varchar(200),
	`is_live` tinyint NOT NULL DEFAULT 0,
	`waba_expiry_date` date,
	`waba_expiry_action_date` datetime,
	`can_send_msg_on_waba` char(1) NOT NULL DEFAULT 'N',
	`portal_ipaddress` varchar(100),
	`portal_flag` tinyint NOT NULL DEFAULT 0,
	CONSTRAINT `tbl_employees_emp_id` PRIMARY KEY(`emp_id`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_incoming_reply_response_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_admin_id` int NOT NULL,
	`template_id` int NOT NULL DEFAULT 0,
	`api_url` text,
	`api_url_use` varchar(100),
	`json_data` text,
	`json_response` text,
	`receive_date` datetime,
	CONSTRAINT `whatsapp_incoming_reply_response_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_incoming_reply_response` (
	`sl` int AUTO_INCREMENT NOT NULL,
	`response` text NOT NULL,
	`name` varchar(255) NOT NULL,
	`actual_name` varchar(255),
	`tmp_name` varchar(255),
	`mobile` varchar(255) NOT NULL,
	`type` char(1) NOT NULL DEFAULT 'N',
	`text` text NOT NULL,
	`converted_text` text,
	`text_language` char(30),
	`user_answer` text,
	`waNumber` varchar(255) NOT NULL,
	`account_id` int NOT NULL DEFAULT 0,
	`send_by` int NOT NULL,
	`user_admin_id` int NOT NULL,
	`lead_id` int NOT NULL DEFAULT 0,
	`is_lead_que_ans_update` enum('Y','N') NOT NULL DEFAULT 'N',
	`msgtype` enum('N','R','S') NOT NULL DEFAULT 'N',
	`readStatus` enum('U','R') NOT NULL DEFAULT 'U',
	`media_type` varchar(255) NOT NULL,
	`image_url` text NOT NULL,
	`source_type` text NOT NULL,
	`source_id` varchar(255) NOT NULL,
	`template_sent_status` enum('N','Y') NOT NULL DEFAULT 'N',
	`template_sent_date` date NOT NULL,
	`template_sent_time` time NOT NULL,
	`template_delivered_status` enum('N','Y') NOT NULL DEFAULT 'N',
	`template_delivered_date` date NOT NULL,
	`template_delivered_time` time NOT NULL,
	`template_read_status` enum('N','Y') NOT NULL DEFAULT 'N',
	`template_read_date` date NOT NULL,
	`template_read_time` time NOT NULL,
	`template_failed_status` enum('N','Y') NOT NULL DEFAULT 'N',
	`template_failed_date` date NOT NULL,
	`template_failed_time` time NOT NULL,
	`body` varchar(255) NOT NULL,
	`ctwa_clid` varchar(255) NOT NULL,
	`headline` varchar(255) NOT NULL,
	`source_url` text NOT NULL,
	`replyrecvdate` datetime NOT NULL,
	`recvDate` datetime NOT NULL,
	`template_catg` char(1) NOT NULL DEFAULT 'N',
	`template_vendor` char(1) NOT NULL DEFAULT 'N',
	`tid` varchar(255) NOT NULL,
	`is_insert` char(1) NOT NULL DEFAULT 'N',
	`insert_date` datetime NOT NULL,
	`status` char(1) NOT NULL DEFAULT 'N',
	`stopService` enum('N','Y') NOT NULL DEFAULT 'N',
	`vendor_type` enum('G','C','A') NOT NULL DEFAULT 'G',
	`journey_type` enum('Y','N') NOT NULL DEFAULT 'N',
	`tempSta` char(1) NOT NULL DEFAULT 'N',
	`paid_template` char(1) NOT NULL DEFAULT 'F',
	`template_sent_status_onaction` char(1) NOT NULL DEFAULT 'N',
	`template_sent_status_date` date NOT NULL,
	`template_sent_amount_mktg` float(10,4) NOT NULL,
	`template_sent_amount_utlty` float(10,4) NOT NULL,
	`wa_utility_amt` float(10,4) NOT NULL,
	`wa_mktg_amt` float(10,4) NOT NULL,
	`not_now_later` enum('N','Y') NOT NULL DEFAULT 'N',
	`country_code` int NOT NULL DEFAULT 91,
	`auto_message` char(1) NOT NULL DEFAULT 'N',
	`temp_status` char(1) NOT NULL DEFAULT 'N',
	`auto_template_count` tinyint NOT NULL,
	`auto_template_message_sent` char(1) NOT NULL DEFAULT 'N',
	`auto_template_failed_date` date NOT NULL,
	`is_run_program` tinyint NOT NULL DEFAULT 0,
	CONSTRAINT `whatsapp_incoming_reply_response_sl` PRIMARY KEY(`sl`)
);
