CREATE TABLE `tbl_account_addresses` (
	`address_id` int AUTO_INCREMENT NOT NULL,
	`account_id` int NOT NULL,
	`billing_address` varchar(250) NOT NULL,
	`billing_city` varchar(50) NOT NULL,
	`billing_pincode` varchar(10) NOT NULL,
	`billing_street` varchar(250) NOT NULL,
	`billing_state` varchar(50) NOT NULL,
	`billing_country` int NOT NULL,
	`shipping_address` varchar(250) NOT NULL,
	`shipping_city` varchar(250) NOT NULL,
	`shipping_pincode` varchar(10) NOT NULL,
	`shipping_street` varchar(250) NOT NULL,
	`shipping_state` varchar(50) NOT NULL,
	`shipping_country` int NOT NULL,
	`is_shift` tinyint NOT NULL DEFAULT 0,
	`masterID` int NOT NULL DEFAULT 0,
	CONSTRAINT `tbl_account_addresses_address_id` PRIMARY KEY(`address_id`)
);
--> statement-breakpoint
CREATE TABLE `tbl_activity` (
	`activity_id` int AUTO_INCREMENT NOT NULL,
	`created_by` int NOT NULL,
	`user_admin_id` int NOT NULL DEFAULT 0,
	`old_user_admin_id` int,
	`activity_type` enum('1','2','3','4') NOT NULL,
	`subject` varchar(255) NOT NULL,
	`due_date` datetime NOT NULL,
	`priority` int NOT NULL,
	`owner` int NOT NULL,
	`contact_name` enum('1','2') NOT NULL,
	`lead_or_contact_id` int,
	`realted_to` enum('1','2') NOT NULL,
	`account_or_deal_id` int,
	`task_status` int NOT NULL,
	`description` text NOT NULL,
	`start_due_date` date NOT NULL,
	`start_due_time` varchar(20) NOT NULL,
	`end_due_date` date NOT NULL,
	`end_due_time` varchar(20) NOT NULL,
	`location` varchar(100) NOT NULL,
	`country` int NOT NULL,
	`participants` int NOT NULL,
	`call_purpose` int NOT NULL,
	`call_type` int NOT NULL,
	`call_detail` int NOT NULL,
	`call_result` int NOT NULL,
	`active_status` enum('1','2') NOT NULL DEFAULT '1',
	`unattendent` int NOT NULL DEFAULT 0,
	`is_checked_attendent` int NOT NULL DEFAULT 0,
	`posted_deal_or_lead` int NOT NULL,
	`created_at` datetime NOT NULL,
	`modified_at` datetime NOT NULL,
	`status` enum('0','1','2','3') NOT NULL DEFAULT '1',
	`tempSta` enum('Y','N') NOT NULL DEFAULT 'N',
	`followup_add_by` enum('N','A','C') NOT NULL DEFAULT 'N',
	`agent_id` int NOT NULL DEFAULT 0,
	`is_delete` int NOT NULL DEFAULT 1,
	`is_sprt_followup` enum('A','S') NOT NULL DEFAULT 'A',
	CONSTRAINT `tbl_activity_activity_id` PRIMARY KEY(`activity_id`)
);
--> statement-breakpoint
CREATE TABLE `tbl_company_details` (
	`company_dtl_id` int AUTO_INCREMENT NOT NULL,
	`employee_id` int NOT NULL,
	`company_name` varchar(255) NOT NULL,
	`logo` varchar(255),
	`employee_count` varchar(6) NOT NULL,
	`comp_phone` varchar(20) NOT NULL,
	`comp_mobile` varchar(15),
	`comp_email` varchar(100),
	`comp_fax` varchar(20),
	`comp_website` varchar(100),
	`superadmin` int NOT NULL,
	`comp_description` text,
	`is_gstin` enum('Y','N') NOT NULL DEFAULT 'N',
	`comp_street` text,
	`comp_state` varchar(100),
	`comp_city` varchar(100),
	`comp_zip_code` varchar(10),
	`comp_country` int,
	`tmp_comp_country` int,
	`bank_holder_name` varchar(100),
	`bank_name` varchar(100),
	`bank_acc_no` varchar(20),
	`bank_branch_name` varchar(100) NOT NULL,
	`bank_ifsc_code` varchar(100),
	`bank_swift_code` varchar(20),
	`invoice_qr_code` varchar(255),
	`invoice_signature` varchar(100),
	`sedex_code` varchar(150),
	`inv_tc` text NOT NULL,
	`sales_inv_tc` text,
	`wa_auto_response_msg` text,
	`gstin` varchar(255) NOT NULL,
	`set_gst_label` varchar(20) NOT NULL DEFAULT 'GST',
	`brn_crn_number` varchar(50),
	`wa_prevw_response_msg` text NOT NULL,
	`autoRespDisp` char(1) NOT NULL DEFAULT 'P',
	`auto_sent_msg` char(1) NOT NULL DEFAULT 'N',
	`auto_sent_msg_days` varchar(50),
	CONSTRAINT `tbl_company_details_company_dtl_id` PRIMARY KEY(`company_dtl_id`)
);
--> statement-breakpoint
CREATE TABLE `tbl_contacts` (
	`contact_id` int AUTO_INCREMENT NOT NULL,
	`created_by` int,
	`user_admin_id` int NOT NULL,
	`old_user_admin_id` int,
	`contact_pic` varchar(100),
	`contact_owner` int,
	`lead_source` int,
	`title` varchar(10),
	`first_name` varchar(255),
	`last_name` varchar(255),
	`account_name` int,
	`email` varchar(100),
	`department` int,
	`phone` varchar(18),
	`home_phone` varchar(18),
	`ohter_phone` varchar(18),
	`fax` varchar(18),
	`mobile` varchar(14),
	`dob` date,
	`assistant` varchar(50),
	`asst_phone` varchar(18),
	`ohter_mobile_no` varchar(18),
	`skype_id` varchar(100),
	`secondary_email` varchar(150),
	`twitter` varchar(150),
	`reporting_to` int,
	`mailing_address` text,
	`mailing_street` text,
	`mailing_city` varchar(80),
	`mailing_state` varchar(80),
	`mailing_postcode` varchar(10),
	`mailing_country` int,
	`description` text,
	`created_at` datetime NOT NULL,
	`modify_at` datetime NOT NULL,
	`status` int NOT NULL DEFAULT 1,
	`is_shift` tinyint NOT NULL DEFAULT 0,
	`masterID` int DEFAULT 0,
	`vendor_id` int NOT NULL DEFAULT 0,
	`mail_status` char(1) NOT NULL DEFAULT 'N',
	`mail_date` date NOT NULL,
	`mail_time` time NOT NULL,
	CONSTRAINT `tbl_contacts_contact_id` PRIMARY KEY(`contact_id`)
);
--> statement-breakpoint
CREATE TABLE `fbinq_forwarding_tbl` (
	`slno` int AUTO_INCREMENT NOT NULL,
	`emp_id` int NOT NULL,
	`user_admin_id` int NOT NULL,
	`for_source_id` varchar(255) NOT NULL,
	`emp_name` varchar(50) NOT NULL,
	`emp_email` varchar(80) NOT NULL,
	`shift_status` char(1) NOT NULL DEFAULT 'N',
	`ptype` char(10) NOT NULL,
	`status` varchar(1) NOT NULL DEFAULT 'N',
	`created_at` datetime NOT NULL,
	`modified_dt` datetime NOT NULL,
	`lead_shift_status` varchar(2) NOT NULL DEFAULT 'N',
	CONSTRAINT `fbinq_forwarding_tbl_slno` PRIMARY KEY(`slno`)
);
--> statement-breakpoint
CREATE TABLE `tbl_lead_source` (
	`sid` int AUTO_INCREMENT NOT NULL,
	`created_by` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`fb_heading_name` varchar(255) NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`status` enum('0','1','2') NOT NULL DEFAULT '1',
	`is_default` int NOT NULL DEFAULT 0,
	`api_type` varchar(255) NOT NULL,
	`old_source_id` int NOT NULL DEFAULT 0,
	CONSTRAINT `tbl_lead_source_sid` PRIMARY KEY(`sid`)
);
--> statement-breakpoint
CREATE TABLE `tbl_leads` (
	`lead_id` int AUTO_INCREMENT NOT NULL,
	`added_by` int NOT NULL,
	`user_admin_id` int NOT NULL,
	`account_id` int,
	`member_type` int NOT NULL DEFAULT 0,
	`account_id_md5` varchar(35) NOT NULL,
	`contact_id` int NOT NULL,
	`lead_status` varchar(11) NOT NULL,
	`lead_title` varchar(255),
	`website` varchar(255) NOT NULL,
	`name_title` varchar(5) NOT NULL,
	`first_name` varchar(255) NOT NULL,
	`last_name` varchar(50) NOT NULL,
	`company` varchar(50) NOT NULL,
	`company_id` int,
	`email` varchar(100) NOT NULL,
	`industry` int NOT NULL,
	`fax` varchar(15) NOT NULL,
	`phone` varchar(100) NOT NULL,
	`mobile` varchar(100) NOT NULL,
	`alternate_mobile` varchar(20),
	`no_of_employee` int NOT NULL,
	`lead_source` varchar(50) NOT NULL,
	`old_lead_source` varchar(50),
	`lead_owner` int NOT NULL,
	`rating` varchar(10) NOT NULL,
	`address` text NOT NULL,
	`street` varchar(255) NOT NULL,
	`city` varchar(50) NOT NULL,
	`state` varchar(50) NOT NULL,
	`post_code` varchar(10) NOT NULL,
	`country` int NOT NULL,
	`ctry_isd_code` varchar(10) NOT NULL DEFAULT '91',
	`description` text NOT NULL,
	`followup_priority` int NOT NULL,
	`lead_last_notes_title` varchar(255),
	`lead_last_notes` text,
	`is_deal` enum('1','2') NOT NULL DEFAULT '2',
	`unattendent` int NOT NULL,
	`is_checked_attendent` int NOT NULL DEFAULT 0,
	`created_at` datetime NOT NULL,
	`shifted_date` datetime,
	`status` enum('0','1','2') NOT NULL DEFAULT '1',
	`is_shift` tinyint NOT NULL DEFAULT 0,
	`masterID` int DEFAULT 0,
	`due_date` datetime,
	`next_due_date` date NOT NULL,
	`next_due_date_add_by` enum('N','A','C') NOT NULL DEFAULT 'N',
	`department` int,
	`lead_sourc_type` char(4) NOT NULL,
	`lead_source_id` bigint NOT NULL,
	`is_api` tinyint DEFAULT 0,
	`contact_status` char(1) NOT NULL DEFAULT 'N',
	`follow_up_add` char(1) NOT NULL DEFAULT 'N',
	`lead_touch_status` char(1) NOT NULL DEFAULT 'N',
	`fb_page_name` varchar(255),
	`webhook_insert_id` int NOT NULL DEFAULT 0,
	`alternate_mbl_upd_dt` datetime NOT NULL,
	`get_lead_from_fb` enum('N','C') DEFAULT 'N',
	`chat_question_answer` text,
	`fresh_pty_status` char(1) NOT NULL DEFAULT 'Y',
	`sent_wa_template_id` varchar(255) NOT NULL,
	`wa_template_count` int NOT NULL,
	`wa_template_sent_dt` datetime NOT NULL,
	`tempSta` char(1) NOT NULL DEFAULT 'N',
	`is_xls` enum('Y','N') NOT NULL DEFAULT 'N',
	`auto_template_sent_date` date NOT NULL,
	`auto_template_sent_status` char(1) NOT NULL DEFAULT 'N',
	CONSTRAINT `tbl_leads_lead_id` PRIMARY KEY(`lead_id`)
);
--> statement-breakpoint
CREATE TABLE `tbl_stages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`old_stage_id` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`user_admin_id` int NOT NULL,
	`status` int NOT NULL,
	`sort_order` int NOT NULL DEFAULT 0,
	`is_default` int NOT NULL,
	`stage_type` char(1) NOT NULL DEFAULT 'N',
	`section_type` enum('L','D') NOT NULL DEFAULT 'D',
	`created_on` datetime NOT NULL,
	CONSTRAINT `tbl_stages_id` PRIMARY KEY(`id`)
);
