import { mysqlTable, int, varchar, text, datetime, tinyint, mysqlEnum } from 'drizzle-orm/mysql-core'

/**
 * Maps `tbl_account` exactly as it exists in the live database (introspected via
 * SHOW CREATE TABLE) — the CRM's customer/account record. Used here only to resolve
 * a WhatsApp contact's display name and STOP-service state by phone number.
 */
export const account = mysqlTable('tbl_account', {
  accountId: int('account_id').autoincrement().primaryKey(),
  accountIdMd5: varchar('account_id_md5', { length: 35 }).notNull(),
  leadId: int('lead_id'),
  vendorId: int('vendor_id'),
  userType: int('user_type').notNull().default(1), // 1=Customer, 2=Vendor
  createdBy: int('created_by').notNull(),
  userAdminId: int('user_admin_id').notNull(),
  oldUserAdminId: int('old_user_admin_id'),
  accountName: varchar('account_name', { length: 255 }).notNull(),
  contactPersonName: varchar('contact_person_name', { length: 255 }).notNull(),
  acType: int('ac_type').notNull(),
  custType: int('cust_type').notNull().default(1),
  memberType: int('member_type').notNull().default(0),
  website: varchar('website', { length: 100 }).notNull(),
  email: varchar('email', { length: 100 }).notNull(),
  fax: varchar('fax', { length: 20 }).notNull(),
  industry: int('industry').notNull(),
  annualRevenue: int('annual_revenue').notNull(),
  accountOwner: int('account_owner').notNull(),
  parentAccount: int('parent_account').notNull(),
  rating: int('rating').notNull(),
  phone: varchar('phone', { length: 100 }).notNull(),
  alternatePhone: varchar('alternate_phone', { length: 20 }),
  ownership: int('ownership').notNull(),
  noOfEmployee: int('no_of_employee').notNull(),
  sicCode: varchar('sic_code', { length: 50 }).notNull(),
  description: text('description').notNull(),
  createdAt: datetime('created_at').notNull(),
  status: int('status').notNull(),
  isShift: tinyint('is_shift').notNull().default(0),
  masterId: int('masterID').default(0),
  gstUinNumber: varchar('gst_uin_number', { length: 40 }),
  stateCode: varchar('state_code', { length: 50 }).notNull(),
  panItNumber: varchar('pan_it_number', { length: 40 }),
  companyLogo: varchar('company_logo', { length: 80 }),
  address: varchar('address', { length: 255 }),
  state: varchar('state', { length: 40 }),
  country: varchar('country', { length: 40 }),
  ctryIsdCode: varchar('ctry_isd_code', { length: 10 }).notNull().default('91'),
  zipcode: varchar('zipcode', { length: 10 }),
  bankName: varchar('bank_name', { length: 40 }),
  bankBranch: varchar('bank_branch', { length: 40 }),
  accountNumber: varchar('account_number', { length: 40 }),
  ifscCode: varchar('ifsc_code', { length: 20 }),
  accountUniqueId: varchar('account_unique_id', { length: 20 }),
  source: int('source').notNull(),
  oldSource: int('old_source').notNull().default(0),
  fbPageName: varchar('fb_page_name', { length: 255 }).notNull(),
  dealsIn: text('deals_in').notNull(),
  stopService: mysqlEnum('stopService', ['N', 'Y']).notNull().default('N'),
  stopServiceDate: datetime('stopServiceDate'),
  unblockServiceDate: datetime('unblockServiceDate'),
  notNowLater: mysqlEnum('not_now_later', ['N', 'Y']).notNull().default('N'),
  sentWaTemplateId: varchar('sent_wa_template_id', { length: 255 }).notNull(),
  waTemplateCount: int('wa_template_count').notNull(),
  waTemplateSentDt: datetime('wa_template_sent_dt').notNull(),
  isXls: mysqlEnum('is_xls', ['Y', 'N']).notNull().default('N'),
  isShiftPortal: varchar('is_shift_portal', { length: 20 }).notNull().default('N'),
  isDeleted: tinyint('is_deleted').notNull().default(0),
})
