import { mysqlTable, int, varchar, text, char, mysqlEnum } from 'drizzle-orm/mysql-core'

/** Maps `tbl_company_details` — only `wa_auto_response_msg`/`autoRespDisp` are used here (the configured canned auto-reply sent on every inbound message when enabled). */
export const companyDetails = mysqlTable('tbl_company_details', {
  companyDtlId: int('company_dtl_id').autoincrement().primaryKey(),
  employeeId: int('employee_id').notNull(),
  companyName: varchar('company_name', { length: 255 }).notNull(),
  logo: varchar('logo', { length: 255 }),
  employeeCount: varchar('employee_count', { length: 6 }).notNull(),
  compPhone: varchar('comp_phone', { length: 20 }).notNull(),
  compMobile: varchar('comp_mobile', { length: 15 }),
  compEmail: varchar('comp_email', { length: 100 }),
  compFax: varchar('comp_fax', { length: 20 }),
  compWebsite: varchar('comp_website', { length: 100 }),
  superadmin: int('superadmin').notNull(),
  compDescription: text('comp_description'),
  isGstin: mysqlEnum('is_gstin', ['Y', 'N']).notNull().default('N'),
  compStreet: text('comp_street'),
  compState: varchar('comp_state', { length: 100 }),
  compCity: varchar('comp_city', { length: 100 }),
  compZipCode: varchar('comp_zip_code', { length: 10 }),
  compCountry: int('comp_country'),
  tmpCompCountry: int('tmp_comp_country'),
  bankHolderName: varchar('bank_holder_name', { length: 100 }),
  bankName: varchar('bank_name', { length: 100 }),
  bankAccNo: varchar('bank_acc_no', { length: 20 }),
  bankBranchName: varchar('bank_branch_name', { length: 100 }).notNull(),
  bankIfscCode: varchar('bank_ifsc_code', { length: 100 }),
  bankSwiftCode: varchar('bank_swift_code', { length: 20 }),
  invoiceQrCode: varchar('invoice_qr_code', { length: 255 }),
  invoiceSignature: varchar('invoice_signature', { length: 100 }),
  sedexCode: varchar('sedex_code', { length: 150 }),
  invTc: text('inv_tc').notNull(),
  salesInvTc: text('sales_inv_tc'),
  waAutoResponseMsg: text('wa_auto_response_msg'),
  gstin: varchar('gstin', { length: 255 }).notNull(),
  setGstLabel: varchar('set_gst_label', { length: 20 }).notNull().default('GST'),
  brnCrnNumber: varchar('brn_crn_number', { length: 50 }),
  waPrevwResponseMsg: text('wa_prevw_response_msg').notNull(),
  autoRespDisp: char('autoRespDisp', { length: 1 }).notNull().default('P'),
  autoSentMsg: char('auto_sent_msg', { length: 1 }).notNull().default('N'),
  autoSentMsgDays: varchar('auto_sent_msg_days', { length: 50 }),
})
