import { mysqlTable, int, varchar, text, char, mysqlEnum, date, datetime, tinyint } from 'drizzle-orm/mysql-core'

/**
 * Maps `tbl_employees` exactly as it exists in the live database (introspected via
 * SHOW CREATE TABLE) — CRM agents, including their WhatsApp Business (WABA) config.
 * Used here to resolve the acting agent's WABA number/vendor/API credentials.
 */
export const employees = mysqlTable('tbl_employees', {
  empId: int('emp_id').autoincrement().primaryKey(),
  memKey: varchar('mem_key', { length: 100 }),
  createdBy: int('created_by').notNull(),
  parentId: int('parent_id').notNull(),
  userType: mysqlEnum('user_type', ['1', '2']).notNull().default('2'), // 1=super admin, 2=employee
  registerType: mysqlEnum('register_type', ['D', 'T', 'R', 'P']).notNull().default('D'),
  portalName: varchar('portal_name', { length: 50 }).notNull().default('WI'),
  title: varchar('title', { length: 10 }),
  firstName: varchar('first_name', { length: 50 }).notNull(),
  middleName: varchar('middle_name', { length: 50 }),
  lastName: varchar('last_name', { length: 50 }).notNull(),
  email: varchar('email', { length: 100 }).notNull(),
  oldEmail: varchar('old_email', { length: 100 }),
  password: varchar('password', { length: 50 }).notNull(),
  phoneNumber: varchar('phone_number', { length: 15 }),
  designation: int('designation').notNull(),
  signatureDesignation: varchar('signature_designation', { length: 255 }).notNull(),
  address: varchar('address', { length: 255 }),
  bankDetails: text('bank_details'),
  isdCode: int('isd_code').notNull().default(0),
  timezone: varchar('timezone', { length: 200 }).notNull().default('Asia/Kolkata'),
  tmpIsdCode: int('tmp_isd_code'),
  tmpTimezone: varchar('tmp_timezone', { length: 255 }),
  userLimit: int('user_limit').notNull(),
  dealStageLimit: int('deal_stage_limit').notNull().default(15),
  leadStageLimit: int('lead_stage_limit').notNull().default(15),
  createdAt: datetime('created_at').notNull(),
  lastLoginDate: varchar('last_login_date', { length: 30 }),
  currentLogin: varchar('current_login', { length: 30 }),
  defaultCurrency: int('default_currency'),
  defaultCurrencyName: varchar('default_currency_name', { length: 50 }),
  timeSlot: int('time_slot').notNull(),
  workingDays: varchar('working_days', { length: 50 }).notNull(),
  isVerified: mysqlEnum('is_verified', ['1', '2']).notNull().default('2'),
  status: mysqlEnum('status', ['0', '1', '2']).notNull().default('1'), // 0=Inactive, 1=Active, 2=Deleted
  statusDtTm: datetime('status_dt_tm'),
  paidStatus: int('paid_status').notNull().default(0),
  verifiedDtTm: datetime('verified_dt_tm').notNull(),
  autoRegsFromEi: tinyint('auto_regs_from_ei').notNull().default(0),
  apiKeyEi: varchar('api_key_ei', { length: 255 }).notNull(),
  membershipEndDate: date('membership_end_date').notNull(),
  extendExpiryDate: date('extend_expiry_date').notNull(),
  sevenDayMailStatus: mysqlEnum('seven_day_mail_status', ['Y', 'N']).notNull().default('N'),
  threeDayMailStatus: mysqlEnum('three_day_mail_status', ['Y', 'N']).notNull().default('N'),
  oneDayMailStatus: mysqlEnum('one_day_mail_status', ['Y', 'N']).notNull().default('N'),
  invoiceTemplate: int('invoice_template').notNull().default(1),
  callingMembership: char('calling_membership', { length: 1 }).notNull().default('N'),
  callingUsername: varchar('calling_username', { length: 255 }).notNull(),
  calligPassword: varchar('callig_password', { length: 255 }).notNull(),
  callingExtn: int('calling_extn').notNull(),
  suppAmtShow: char('supp_amt_show', { length: 1 }).notNull().default('N'),
  salesInvPrefixTxt: varchar('sales_inv_prefix_txt', { length: 30 }),
  purchaseInvPrefixTxt: varchar('purchase_inv_prefix_txt', { length: 30 }),
  creditInvPrefixTxt: varchar('credit_inv_prefix_txt', { length: 30 }),
  debitInvPrefixTxt: varchar('debit_inv_prefix_txt', { length: 30 }),
  salesOrderPrefixTxt: varchar('sales_order_prefix_txt', { length: 30 }),
  purchaseOrderPrefixTxt: varchar('purchase_order_prefix_txt', { length: 30 }),
  performaInvPrefixTxt: varchar('performa_inv_prefix_txt', { length: 30 }),
  deliveryNotePrefixTxt: varchar('delivery_note_prefix_txt', { length: 30 }),
  loginidChgDt: datetime('loginid_chg_dt').notNull(),
  isPopShowAcnt: tinyint('is_pop_show_acnt').default(0),
  whatsappNoOptin: char('whatsapp_no_optin', { length: 1 }).notNull().default('N'),
  whatsappSendFromWi: char('whatsapp_send_from_wi', { length: 1 }).notNull().default('N'),
  whatsappSendFromWiDt: datetime('whatsapp_send_from_wi_dt').notNull(),
  whatsappPermission: char('whatsapp_permission', { length: 1 }).notNull().default('N'),
  whatsappWabano: varchar('whatsapp_wabano', { length: 255 }).notNull(),
  oldWhatsappWabano: varchar('old_whatsapp_wabano', { length: 255 }).notNull(),
  whatsappVendor: char('whatsapp_vendor', { length: 1 }).notNull().default('N'), // N:Default, G:Gupshup, C:Netcore, A:AiSensy
  whatsappApiUsername: text('whatsapp_api_username').notNull(),
  whatsappApiPassword: varchar('whatsapp_api_password', { length: 255 }).notNull(),
  wpType: mysqlEnum('wp_type', [
    'crm', 'erp', 'ecom', 'pi', 'eismo', 'reismo', 'ttwsmo', 'pismo', 'wlsmo', 'ttw', 'O', 'N',
  ]).notNull().default('N'),
  whatsappAppId: varchar('whatsapp_app_id', { length: 255 }).notNull(),
  waLoginUsername: varchar('wa_login_username', { length: 255 }).notNull(),
  waApiKeyDt: date('wa_api_key_dt').notNull(),
  waTokenExpDt: datetime('wa_token_exp_dt').notNull(),
  whatsappBulkPermission: mysqlEnum('whatsapp_bulk_permission', ['N', 'Y']).notNull().default('N'),
  whatsappTemplateLimit: int('whatsapp_template_limit').notNull(),
  tempSta: char('tempSta', { length: 1 }).notNull().default('N'),
  tempMailSent: char('temp_mail_sent', { length: 1 }).notNull().default('N'),
  waMemberType: char('wa_member_type', { length: 1 }).notNull().default('N'),
  waEmpMemType: int('wa_emp_mem_type').notNull(),
  wabaActivated: char('waba_activated', { length: 1 }).notNull().default('N'),
  wpMmLiteEnabled: char('wp_mm_lite_enabled', { length: 1 }).notNull().default('N'),
  customerType: char('customer_type', { length: 1 }).notNull().default('N'),
  domainUrl: varchar('domain_url', { length: 200 }),
  isLive: tinyint('is_live').notNull().default(0),
  wabaExpiryDate: date('waba_expiry_date'),
  wabaExpiryActionDate: datetime('waba_expiry_action_date'),
  canSendMsgOnWaba: char('can_send_msg_on_waba', { length: 1 }).notNull().default('N'),
  portalIpaddress: varchar('portal_ipaddress', { length: 100 }),
  portalFlag: tinyint('portal_flag').notNull().default(0),
})
